### ISSUE TITLE
Indigo version

### ISSUE THREAD

**Issue by NikolausDemmel** [ipa320/rqt_frame_editor_plugin#1]
Just came here from the ros users announcement. Thanks for this package! I'd like to try it. Could you maybe tag an indigo compatible commit as you mentioned? Or create the `indigo-devel` branch on that commit.

**Comment by ipa-lth** [comment]
Here we go. I am happy to provide something you can use :-).

The indigo version worked well for us quite long. But further development will happen on the kinetic branch.
